name: Java CI with Gradle

on:
  push:
    paths:
      - 'Lab3/VBasicCompiler/**'
    branches:
      - main
      - lab-3-marharyta-prachuk
  pull_request:
    paths:
      - 'Lab3/VBasicCompiler/**'
    branches:
      - main
      - lab-3-marharyta-prachuk

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '21'

    - name: Verify gradlew presence
      run: ls -la Lab3/VBasicCompiler

    - name: Make gradlew executable
      run: chmod +x Lab3/VBasicCompiler/gradlew

    - name: Build
      working-directory: Lab3/VBasicCompiler
      run: ./gradlew build -x test

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '21'

    - name: Verify gradlew presence
      run: ls -la Lab3/VBasicCompiler

    - name: Make gradlew executable
      run: chmod +x Lab3/VBasicCompiler/gradlew

    - name: Run tests
      working-directory: Lab3/VBasicCompiler
      run: ./gradlew test
